### PR TITLE
fix: converted output of random sampler to numpy array

### PR DESCRIPTION
**Pull request by musslick**
# Description

Converted output of random sampler to numpy array

# Type of change
- **fix**: A bug fix

### CODE REVIEW

**Comment by hollandjg** [comment]
please have a look at #17 – that shows an example of how to handle the pd.DataFrame conversion using the Variables for the grid pooler.

**Comment by benwandrew** [comment]
sorry, but what is the current status/relevance of this PR?

**Comment by benwandrew** [comment]
bumping this @musslick. still relevant?

**Comment by benwandrew** [comment]
can we close this?

**Comment by younesStrittmatter** [comment]
not relevant anymore can be closed

**Pull request closed without merging**
